name: aav
channels:
  - defaults
dependencies:
  - asttokens=2.0.5
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - colorama=0.4.6
  - comm=0.2.1
  - cudatoolkit=11.8.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.6.4
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=2.2.2
  - numpy-base=2.2.2
  - openssl=3.0.16
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pip=25.0
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.13
  - pytz=2024.1
  - pywin32=308
  - pyzmq=26.2.0
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - tzdata=2025a
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.5
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.56.0
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - networkx==3.3
      - pillow==11.0.0
      - pyparsing==3.2.1
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - tqdm==4.67.1
      - typing-extensions==4.12.2

